### ISSUE TITLE
Layout: New Features

### ISSUE THREAD

**Issue by CampConn** [cs361fall2017/team6#12]
In order to match our design, a couple of new features need to be added:
- A discard pile that can be viewed by the player
- A score display that goes up by 1 whenever a card is removed
- A new game button that clears the table, rebuilds the deck and shuffles it, and makes the first deal

The score is already tracked as a variable, so all that needs added is the display.

**Comment by NWCampbell** [comment]
Discard pile is viewable, score is displayed prominently, new game button "functions" as a way of refreshing the page simulating a rebuild, shuffle and deal.
