### ISSUE TITLE
Layout: Arrangement

### ISSUE THREAD

**Issue by CampConn** [cs361fall2017/team6#13]
The layout needs to be rearranged to match the agreed upon design. Specifically:
- The deal button should be in the top left, just under the title
- Depending on what order the issues are handled in, the score display may need to be moved to the right of the deal button, above the columns. The discard pile will be to the right of the score, on the same level as the deal button
- Ideally, they'll be removed when we implement mouse clicking functionality on the cards, but until that's complete it'd be better if the remove buttons were in line with their respective piles

**Comment by NWCampbell** [comment]
Deal Button Placed correctly, score is placed ideally, discard pile is placed correctly and the move functionality while not being click working is aesthetically pleasing.
