### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by CampConn** [cs361fall2017/team6#14]
Because pressing buttons and typing in numbers is stupid, we should attempt to add mouse clicking functionality. Clicking on a card should result in the following logic:
- If card can be removed, only allow a remove function as moving the card would always be the worst option.
- Highlight / Shadowbox when hovering over a Card element.
- Highlight / Shadowbox available options when hovering over a Card element (Remove or Move locations)
- When the above highlights are active, the game enters a special state that allows the player to choose which of the highlighted spaces the card moves to by clicking one of them (clicking the card again, or a not-highlighted space should cancel to state) ((Think of an option pane that will run a function based on what was selected))

It's not of dire need that these be implemented exactly in this manner, but doing something along these lines will make the overall UI cleaner and more intuitive. Once it is implemented, the remove buttons and move commands can be removed.

**Comment by NWCampbell** [comment]
Added error handling to catch illegal moves, highlights were not completed by sprint's end.

UI is a little more intuitive, but still functionally the same as click functionality was hard to accomplish.

(Closing final issue) This was closed late, as Connor is at his main house at the beach and unable to receive emails/github updates, Sam was called back into work around 6pm and I was at work from 7pm until 12:30am.
