### ISSUE TITLE
Appearances and Clean Up

### ISSUE THREAD

**Issue by CampConn** [cs361fall2017/team6#15]
These fixes will make playing the game feel more intuitive:
- Either remove the column labels once clicking functionality is added, or change them such that the labels, buttons and moving options are consistent
- Make everything centered on the screen

These changes are optional and will make the game feel aesthetically pleasing/more inviting. Only do them after everything else is ready for the deadline:
- Replace the names of the suites with images so the player can tell at a glance what it is. If the Diamonds and Hearts can be made either red or white while the Spades and Clubs are black, that would be even better
- Make it so that 11-14 are displayed as J, Q, K, and A respectively
- Make the cards look like cards. The top cards should a height:width ratio of 7:5, while the others appear mostly covered except for the value and suit
- A background would be nice. Green is common with card games

**Comment by NWCampbell** [comment]
Button functionality was unable to be accomplished in the duration of this sprint, cosmetic effects have been applied such as: Green background, hiding empty card cells on the table, fixing stretching with the discard pile
