### ISSUE TITLE
Fix Deck glitches

### ISSUE THREAD

**Issue by CampConn** [cs361fall2017/team6#31]
The Deck's simpleton design seems to be causing a glitch that prevents the game from restarting after the deck is emptied. Please change it back to what it was. Also, in a test run, we found two 8's of diamonds. Look into that.

**Comment by NWCampbell** [comment]
Game has a temporary patch applied, the Singleton design of the deck is still an issue but is the only thing keeping the deck in line. This is sub-optimal for an online game available to thousands through a server, but as it is a single player at a time makes it functional. Propagation of the deck is no longer happening so no more duplicate cards.
